DROP VIEW NOTICE_VIEW35;


CREATE VIEW NOTICE_VIEW35
AS

SELECT ROWNUM SNUM, N.* FROM
(SELECT  N.CODE, N.TITLE, N.WRITER, N.CONTENT,N.REGDATE, N.HIT, M.NAME as WRITER_NAME, COUNT(C.CODE) CMT_CNT
FROM MEMBER M
RIGHT OUTER JOIN NOTICE N ON M.NAME = N.WRITER
LEFT OUTER JOIN "COMMENT" C ON N.CODE = C.NOTICE_CODE
GROUP BY  N.CODE, N.TITLE, N.WRITER, N.CONTENT,N.REGDATE ,N.HIT, M.NAME
--ORDER BY N.REGDATE DESC;
) N



SELECT * FROM NOTICE_VIEW35 WHERE WRITER = '³ªµÍ´Ï' AND CONTENT like '%¤·%'  


SELECT CODE, TITLE , WRITER FROM NOTICE GROUP BY WRITER;

SELECT * 
FROM (SELECT ROWNUM NUM, N.* FROM NOTICE_VIEW N  WHERE TITLE LIKE '%1%') 
WHERE NUM BETWEEN 1 AND 10;





CREATE VIEW NOTICE_VIEW35
AS

SELECT N.* FROM
(SELECT  N.CODE, N.TITLE, N.WRITER, N.CONTENT,N.REGDATE, N.HIT, M.NAME as WRITER_NAME, COUNT(C.CODE) CMT_CNT
FROM MEMBER M
RIGHT OUTER JOIN NOTICE N ON M.NAME = N.WRITER
LEFT OUTER JOIN "COMMENT" C ON N.CODE = C.NOTICE_CODE
GROUP BY  N.CODE, N.TITLE, N.WRITER, N.CONTENT,N.REGDATE ,N.HIT, M.NAME
--ORDER BY N.REGDATE DESC;
) N





SELECT ROWNUM NUM, N.* FROM NOTICE_VIEW N;



\